/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as adminRouteRouteImport } from './routes/(admin)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authauthEntryRouteRouteImport } from './routes/(auth)/(auth-entry)/route'
import { Route as admindashboardRouteRouteImport } from './routes/(admin)/(dashboard)/route'
import { Route as authauthEntryLoginRouteImport } from './routes/(auth)/(auth-entry)/login'
import { Route as admindashboardDashboardRouteImport } from './routes/(admin)/(dashboard)/dashboard'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRouteRoute = adminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authauthEntryRouteRoute = authauthEntryRouteRouteImport.update({
  id: '/(auth-entry)',
  getParentRoute: () => authRouteRoute,
} as any)
const admindashboardRouteRoute = admindashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => adminRouteRoute,
} as any)
const authauthEntryLoginRoute = authauthEntryLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authauthEntryRouteRoute,
} as any)
const admindashboardDashboardRoute = admindashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => admindashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof admindashboardDashboardRoute
  '/login': typeof authauthEntryLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof admindashboardDashboardRoute
  '/login': typeof authauthEntryLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(admin)': typeof adminRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(admin)/(dashboard)': typeof admindashboardRouteRouteWithChildren
  '/(auth)/(auth-entry)': typeof authauthEntryRouteRouteWithChildren
  '/(admin)/(dashboard)/dashboard': typeof admindashboardDashboardRoute
  '/(auth)/(auth-entry)/login': typeof authauthEntryLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/login'
  id:
    | '__root__'
    | '/'
    | '/(admin)'
    | '/(auth)'
    | '/(admin)/(dashboard)'
    | '/(auth)/(auth-entry)'
    | '/(admin)/(dashboard)/dashboard'
    | '/(auth)/(auth-entry)/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  adminRouteRoute: typeof adminRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/(auth-entry)': {
      id: '/(auth)/(auth-entry)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authauthEntryRouteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(admin)/(dashboard)': {
      id: '/(admin)/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof admindashboardRouteRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(auth)/(auth-entry)/login': {
      id: '/(auth)/(auth-entry)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authauthEntryLoginRouteImport
      parentRoute: typeof authauthEntryRouteRoute
    }
    '/(admin)/(dashboard)/dashboard': {
      id: '/(admin)/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof admindashboardDashboardRouteImport
      parentRoute: typeof admindashboardRouteRoute
    }
  }
}

interface admindashboardRouteRouteChildren {
  admindashboardDashboardRoute: typeof admindashboardDashboardRoute
}

const admindashboardRouteRouteChildren: admindashboardRouteRouteChildren = {
  admindashboardDashboardRoute: admindashboardDashboardRoute,
}

const admindashboardRouteRouteWithChildren =
  admindashboardRouteRoute._addFileChildren(admindashboardRouteRouteChildren)

interface adminRouteRouteChildren {
  admindashboardRouteRoute: typeof admindashboardRouteRouteWithChildren
}

const adminRouteRouteChildren: adminRouteRouteChildren = {
  admindashboardRouteRoute: admindashboardRouteRouteWithChildren,
}

const adminRouteRouteWithChildren = adminRouteRoute._addFileChildren(
  adminRouteRouteChildren,
)

interface authauthEntryRouteRouteChildren {
  authauthEntryLoginRoute: typeof authauthEntryLoginRoute
}

const authauthEntryRouteRouteChildren: authauthEntryRouteRouteChildren = {
  authauthEntryLoginRoute: authauthEntryLoginRoute,
}

const authauthEntryRouteRouteWithChildren =
  authauthEntryRouteRoute._addFileChildren(authauthEntryRouteRouteChildren)

interface authRouteRouteChildren {
  authauthEntryRouteRoute: typeof authauthEntryRouteRouteWithChildren
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authauthEntryRouteRoute: authauthEntryRouteRouteWithChildren,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  adminRouteRoute: adminRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
